version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: fedi
      POSTGRES_DB: database
    ports:
      - "25433:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
